name: Build & publish container

on:
  push:
  workflow_dispatch:  # allow manual runs

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Derive lower-case owner
        id: vars
        run: echo "OWNER_LC=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"

      - name: Log in to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ steps.vars.outputs.OWNER_LC }}/fprime-container:latest
            ghcr.io/${{ steps.vars.outputs.OWNER_LC }}/fprime-container:${{ github.sha }}
